# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Art Brock
email: artbrock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Arthur Brock builds targeted currencies which shape the social dynamics of our emerging post-industrial economy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://artbrock.com" # the base hostname & protocol for your site
locale: "en-US"
contact_url: "/connect/"
twitter_username: metacurrency
github_username:  metacurrency

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  posts:
    output: true
    permalink: /blog/:path
  whitepapers:
    output: true
    permalink: /whitepapers/:slug
  redirects:
    output: true
  projects:
    output: true
    permalink: /projects/:path
  participate:
    output: true
    permalink: /participate/:slug
  collaborations:
    output: true
    permalink: /collaborations/:slug 
  deeper:
    output: true
    permalink: /deeper/:path
  videos:
    output: true
    permalink: /videos/:path
  presentations:
    output: true
    permalink: /presentations/:path
  audio:
    output: true
    permalink: /audio/:path
  publications:
    output: true
    permalink: /publications/:slug 
  news:
    output: true
    permalink: /news/:slug
  resources:
    output: true
    permalink: /resources/:slug
  connect:
    output: true
    permalink: /connect/ 


